POST http://localhost:3001/api/eventos/eduortza HTTP/1.1
Content-Type: application/json

{
    "title": "Reunión de equipo",
    "startDate": "2024-03-12T10:00",
    "endDate": "2024-03-12T12:00",
    "description": "Reunión semanal para discutir los avances del proyecto.",
    "color": "green",
    "group": 1,
    "location": "Sala de reuniones",
    "notes": "No olvidar llevar el informe de ventas.",
    "status": "Active",
    "attachments": "https://www.orimi.com/pdf-test.pdf"
}

###
POST http://localhost:3001/api/recordatorios/eduortza HTTP/1.1
Content-Type: application/json

{
  "recordatorio": {
    "selectedTitle": "Comprar leche",
    "selectedDateStart": "2024-03-09T08:00:00Z",
    "selectedDateEnd": "2024-03-09T08:30:00Z",
    "selectedDescription": "No olvidar comprar leche en el supermercado.",
    "selectedColor": "green"
  }
}

###
GET http://localhost:3001/api/actividades/usuario1 HTTP/1.1

GET http://localhost:3001/api/organizaciones/65f22f1119eb7381c6d37a08 HTTP/1.1

GET http://localhost:3001/api/organizaciones HTTP/1.1