###
POST http://localhost:3000/api/organizations
Content-Type: application/json

{
    "parent_organization_id": null,
    "name": "Nombre de la organización",
    "description": "Descripción de la organización",
    "contact": "Información de contacto",
    "email": "correo@organizacion.com",
    "domain": "www.organizacion.com",
    "privacy": "público"
}


###
POST http://localhost:3000/api/activities
Content-Type: application/json

{
    "organization_id": 1,
    "name": "Nombre de la actividad",
    "description": "Descripción de la actividad",
    "privacy": "privado"
}

### 
POST http://localhost:3000/api/groups
Content-Type: application/json

{
    "organization_id": 1,
    "activity_id": 1, 
    "name": "Nombre del grupo",
    "description": "Descripción del grupo",
    "privacy": "público"
}

### 
POST http://localhost:3000/api/events
Content-Type: application/json

{
    "group_id": 1,
    "title": "Título del evento",
    "description": "Descripción del evento",
    "start_date": "2024-03-25T10:00:00Z",
    "end_date": "2024-03-25T12:00:00Z",
    "location": "Ubicación del evento",
    "repeat": "NONE",
    "notes": "Notas adicionales",
    "status": "CONFIRMED",
    "color": "#FF0000"
}

### 
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
    "fullName": "Antonio Aparicio",
    "email": "antonio@example.com",
    "username": "antonioap101",
    "passwordHash": "hashdecontraseña",
    "timeZone": "GMT"        
}

###
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
"username": "antonioap101",
"passwordHash": "falso"
}

###
POST http://localhost:3000/api/reminders
Content-Type: application/json

{
    "user_id": 1,
    "event_id": 1,
    "title": "Mi recordatorio 1",
    "description": "Descripción del recordatorio",
    "start_date": "2024-03-25T09:00:00Z",
    "end_date": "2024-03-25T09:30:00Z",
    "repeat": "Ninguno",
    "color": "#00FF00"    
}

### 
DELETE http://localhost:3000/api/organizations/1


